behaviors:
  TestBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32          # 약간 늘려서 더 안정적인 학습
      buffer_size: 128        # 빠른 학습을 위해 여전히 작게 유지
      learning_rate: 0.0005   # 약간 증가시켜 학습 속도 개선
      beta: 0.01              # 규제 강도 증가
      epsilon: 0.2
      lambd: 0.92             # 감마와 조화를 이루도록 조정
      num_epoch: 3            # 조금 더 반복 학습
    network_settings:
      num_layers: 1
      hidden_units: 64        # 중간 수준으로 설정
    max_steps: 1000           # 충분한 학습을 위해 스텝 증가
    time_horizon: 64          # 에피소드의 더 많은 컨텍스트를 포함
    summary_freq: 250         # 더 자주 로그 출력으로 결과를 확인
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
